[build]
  publish = "."
  command = "npm run build"
  functions = "functions"

# Branch settings
[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  command = "npm run build"
  environment = { NODE_ENV = "preview" }

[context.branch-deploy]
  command = "echo 'Branch deploy build'"

# API routes for database functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Admin dashboard access
[[redirects]]
  from = "/admin"
  to = "/admin-dashboard.html"
  status = 200

# SPA redirect (keep last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form handling configuration
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https:;"

# Security headers
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Basic build settings
[build.environment]
  NODE_VERSION = "18"
  # Enable Netlify DB (Neon integration)
  NETLIFY_DATABASE_ENABLED = "true"
